name: colab
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    strategy:
      fail-fast: true
    # current colab os
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Get colab environment specification
        run: |
          wget https://raw.githubusercontent.com/googlecolab/backend-info/main/apt-list.txt
          cat apt-list.txt | cut -d'/' -f1 | grep -v "^#" | grep -v "^Listing" > apt-installable.txt
          wget https://github.com/googlecolab/backend-info/raw/main/pip-freeze.txt
          grep -v colabtools pip-freeze.txt > pip-installable.txt

      - name: Install OS packages
        run: sudo apt install $(cat apt-installable.txt)

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"
          cache: "pip"

      - name: Install colab environment
        run: python -m pip install -r pip-installable.txt

      - name: Install malariagen_data
        run: python -m pip install -e .[dev]

      - name: Run fast unit tests
        run: pytest -v tests/anoph --typeguard-packages=malariagen_data,malariagen_data.anoph
