name: tests
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.3.1"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry==${{ matrix.poetry-version }}

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install

      - name: Run mypy
        run: poetry run mypy malariagen_data/anopheles.py --ignore-missing-imports
